### ISSUE TITLE
Recent janus releases on PyPI are missing sdists

### ISSUE THREAD

**Issue by himikof** [aio-libs/janus#20]
According to https://pypi.python.org/simple/janus/, there are only wheels, not tar.gz archives for recent (>= 0.2) releases of janus. This makes it impossible to install in an older packaging environment (missing wheel  support). Could sdist be uploaded on PyPI for recent releases?

**Comment by asvetlov** [comment]
Fixed by 0.2.4

**Comment by himikof** [comment]
Thanks!
