### ISSUE TITLE
Differences in behaviour and API vs. Python Queues

### ISSUE THREAD

**Issue by misterjoa** [aio-libs/janus#212]
Need to confirm, my mistake.
Confused APIs of deques and queues.

**Comment by jettify** [comment]
Not sure I follow your question. `janus` should be compatible with `queue.Queue` and `asyncio.Queue`

**Comment by misterjoa** [comment]
Sorry, I was very tired and my program is using queues and deques. Confirmed everything is working OK API-wise ! You can close this bug report :-) And thank you for this very useful package !

**Comment by asvetlov** [comment]
You are welcome!
