### ISSUE TITLE
Could async_q.get() support a timeout?

### ISSUE THREAD

**Issue by simonw** [aio-libs/janus#240]
Python's `queue.Queue.get()` takes an optional timeout, and will block for up to that amount of time.

Python's `asyncio.Queue.get()` doesn't support this option.

I know Janus is attempting to closely initiate these APIs, but would it be feasible (and a good idea) for Janus to provide a timeout option even when reading from the async queue?

I would love to be able to do this:

    try:
        item = await queue.async_q.get(timeout=0.5)
    except Empty:
        # ...

**Comment by achimnol** [comment]
I think you could add timeout using [async-timeout](https://github.com/aio-libs/async-timeout), which provides more fine-grained control of timeouts as a context-manager style.
