### ISSUE TITLE
Inaccurate dependence python 3.5.3 - because of typing.Deque

### ISSUE THREAD

**Issue by farax4de** [aio-libs/janus#259]
The class [typing.Deque](https://docs.python.org/3/library/typing.html#classes-functions-and-decorators) was first introduced in Python 3.5.4. The parameter for package dependencies should be updated to: python_requires='>=3.5.4'

**Comment by asvetlov** [comment]
you are right, thanks.
Perhaps, the next version should drop Python 3.5 at all :)
Who uses it now?

**Comment by farax4de** [comment]
I noticed this on Debian 9 (stretch), where Python 3.5.3-1 is the latest version.

**Comment by farax4de** [comment]
version 3.5 is now  deprecated

**Comment by farax4de** [comment]
version 3.5 is now  deprecated
