### ISSUE TITLE
Double-ended Queue Support

### ISSUE THREAD

**Issue by ronigober** [aio-libs/janus#427]
Hey!
Recently I found your library and it's really helping me with the communication between sub thread coroutines and main thread functions.
One of my use cases needs the ability to clear all the already exiting messages in a queue,
or to insert the new message to the end of the queue.
That ability is not possible when using a normal queue,
so I wanted to know if there is any planning for a double-ended queue support any time soon.
Thanks!

**Comment by asvetlov** [comment]
Sorry, there is a very low chance that double-ended queue will be implemented.
As a workaround, you can get all queue elements to "clear" it.
