### ISSUE TITLE
No running event loop

### ISSUE THREAD

**Issue by aaronclong** [aio-libs/janus#448]
I am having trouble creating the janus Queue outside of asyncio. It requires me to make dummy background tasks to just create the object, since not running loop exists I am wonder if this could be lazy or allow the loop to be passed in the constructor? It makes sync to async code  a tad harder.

**Comment by blozano824** [comment]
I was able to use janus v0.4.0 successfully but upgrading to v1.0.0 results in the same code raising `RuntimeError: no running event loop`. I haven't been able to pin down the exact change that caused this.

**Comment by lemonJumps** [comment]
From my understanding it needs an existing asyncio loop in main thread in order to work.
I tried to force it to use a loop from separate thread but it didn't like that.

**Comment by lemonJumps** [comment]
actually, I've found this https://github.com/dano/aioprocessing it has a queue that works like a charm. <3

**Comment by jettify** [comment]
I suspect problem as described here https://github.com/aio-libs/janus/pull/438

**Comment by liubanliuhao** [comment]
Any progress of this Issue? Same problem when I creating a queue in the sync function and pass it to the async one.

**Comment by OppOops** [comment]
Simple way to create janus queue in synchronous code (Python 3.6+). 
```py
import asyncio
import janus

def init_janus_queue():
    async def create_queue():
        return janus.Queue()
    loop = asyncio.get_event_loop_policy().get_event_loop()
    return loop.run_until_complete(create_queue())

res_queue = init_janus_queue()
```
