### ISSUE TITLE
doesn't play nicely with concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by FirefighterBlu3** [aio-libs/janus#5]
if loop.run_in_executor(executor,...) is ProcessPoolExecutor instead of None, exceptions will be raised such as inability to serialize thread lock objects and callItems.

**Comment by asvetlov** [comment]
Sure.
Janus was developed to store all data in process local memory only.
It just not intended to support multiprocess approach.
asyncio is not intended too, btw. It works in some scenarios but fails in others.

**Comment by FirefighterBlu3** [comment]
perhaps an instance check w/ exception? it can be frustrating to debug something for a while before figuring out it doesn't work with concurrent.futures.

**Comment by asvetlov** [comment]
I don't follow what place for check are you suggesting.
Would you provide a Pull Request?

**Comment by jettify** [comment]
not active more then year, closing

**Comment by asvetlov** [comment]
Agree
