### ISSUE TITLE
Support an atomic `.clear()` operation.

### ISSUE THREAD

**Issue by maxeonyx** [aio-libs/janus#645]
Hi - I have the following use case:

We have an in-memory `PubSub` class for an SSE streaming web server. Our streams either send patches or full updates to the web client.

To ensure all messages are recieved (important for patch-type messages) we use a small queue per client. However, if this fills up, we can only drop messages. What we do is drop all items in the queue and send a full update.

However, there is no way to atomically clear the queue. Currently we have to use a lock around calling `.get_nowait()` in a loop. This is not ideal as `janus` already has a lock internally.

Would it be possible to add an atomic `.clear()` operation? I understand this is not present in the other implementations that `janus` matches, so if API similarity is a concern then I understand.

Thanks!

**Comment by asvetlov** [comment]
Hello.
Sorry for the late reply.
Since both `queue.Queue` and `asyncio.Queue` don't have `.clear()` there is a very low chance to add such method to janus.

Honestly, I have a feeling that wiping-out the queue is a kind of weak pattern. Can you provide examples of synchronization queue implementations that have desired functionality?

**Comment by maxeonyx** [comment]
No worries about the late reply.

The weakness is true - our use case would be better served with something more purpose-built for a streaming web server - e.g. rather than having a small queue per client and wiping out the queue for slow clients, have some kind of shared queue whose dequeue method takes the client's expected position, and if the client was too slow then returns a different kind of response.

For interest's sake, here is the info about queues in other langs / frameworks:

Implementations of queues with `clear()` functionality:
 - Java: [`java.util.concurrent.ArrayBlockingQueue`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/concurrent/ArrayBlockingQueue.html#clear())
 - Rust (standard library): [`std::collection::VecDeque`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.clear)
 - .NET: [`System.Collections.Generic.Queue`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.queue-1.clear?view=net-8.0#system-collections-generic-queue-1-clear)

Implementations that *don't* have "clear" (in general, "channels" don't have this capability)
- Go (clearing a channel requires a loop)
- Rust [`async_channel crate`](https://docs.rs/async-channel/latest/async_channel/)
- .NET [`System.Threading.Channel`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.channels.channel-1?view=net-8.0)

Implementations with "multiple dequeue" but without "clear" (in my use case, this would then require a check for number of elements and therefore a lock):
- TensorFlow: [`tf.queue.FIFOQueue`](https://www.tensorflow.org/api_docs/python/tf/queue/FIFOQueue)

There's actually not many "async queues" around - mostly either blocking queues, or channels.

**Comment by maxeonyx** [comment]
@x42005e1f Thanks for the info. Having `.clear()` in janus is not necessarily very important to me - a very small performance impact from `.get_nowait()` in a loop instead of a bulk `.clear() (all queues are small in my use-case). I mostly made this issue as it seemed like a gap that might be an easy addition. I will check out your lib, but I can close this issue now that @asvetlov has responded.

**Comment by maxeonyx** [comment]
Closing as not planned:

> Since both queue.Queue and asyncio.Queue don't have .clear() there is a very low chance to add such method to janus.

**Comment by maxeonyx** [comment]
Closing as not planned:

> Since both queue.Queue and asyncio.Queue don't have .clear() there is a very low chance to add such method to janus.
