### ISSUE TITLE
Status of project and performance improvements

### ISSUE THREAD

**Issue by x42005e1f** [aio-libs/janus#679]
As I can see from the commits, there hasn't been a single major change since December 2021, with the maximum changes being config fixes, cleanup of types, and dropping support for Python 3.7. The project's issues are not resolved, and pull requests are still open. So the question is: what is the level of support for this project now?

There's a reason why I'm asking this. I too have implemented queues (as part of a [more general package](https://github.com/x42005e1f/aiologic)) that support communicating between synchronous and asynchronous code, but with a different approach. In simple put-get tests between two threads in both directions, they appear to be ~7x faster on CPython, ~24x faster on PyPy, which mitigates the [performance issue](https://github.com/aio-libs/janus/issues/419). They are not [bound to the event loop](https://github.com/aio-libs/janus/issues/448). They also [support various concurrency libraries](https://github.com/aio-libs/janus/issues/506), and a lot more.

<details>
<summary>janus benchmark</summary>

```python
import asyncio

from threading import Thread

import janus


def work(in_q, out_q):
    while True:
        item = in_q.get()

        if item is None:
            break

        out_q.put(item)


async def func(in_q, out_q):
    ops = 0

    try:
        item = 42

        while True:
            await out_q.put(item)

            ops += 1

            item = await in_q.get()
    finally:
        print(ops)


async def main():
    in_q = janus.Queue()
    out_q = janus.Queue()

    Thread(target=work, args=[out_q.sync_q, in_q.sync_q]).start()

    try:
        await asyncio.wait_for(func(in_q.async_q, out_q.async_q), 6)
    except asyncio.TimeoutError:
        pass
    finally:
        await out_q.async_q.put(None)


asyncio.run(main())
```
</details>

<details>
<summary>aiologic benchmark</summary>

```python
import asyncio

from threading import Thread

import aiologic


def work(in_q, out_q):
    while True:
        item = in_q.green_get()

        if item is None:
            break

        out_q.green_put(item)


async def func(in_q, out_q):
    ops = 0

    try:
        item = 42

        while True:
            await out_q.async_put(item)

            ops += 1

            item = await in_q.async_get()
    finally:
        print(ops)


async def main():
    in_q = aiologic.SimpleQueue()
    out_q = aiologic.SimpleQueue()

    Thread(target=work, args=[out_q, in_q]).start()

    try:
        await asyncio.wait_for(func(in_q, out_q), 6)
    except asyncio.TimeoutError:
        pass
    finally:
        await out_q.async_put(None)


asyncio.run(main())
```
</details>

I need to know what the status of your package is to determine how best to contrast mine with yours.

**Comment by asvetlov** [comment]
Hey!
Thanks for sharing a link to aiologic, it looks interesting!
Regarding janus status, the project is not actively developed but still maintained. The most part of work is about keeping it work with newest Python versions. 
API is stable, I don't see a lot of space for improvements here. The api mimics `queue` and `asyncio` counterparts which are not changed for decade.

Requests for better performance and unbound event loop are reasonable, a pull request is welcome.
anyio support is more questionable. janus provides a bridge between `queue.Queue` compatible and `asyncio.Queue` compatible APIs. From my understanding, `anyio.Queue` doesn't exist. Maybe adding such thing makes sense, I don't know. I personally never use anyio for my job but work with asyncio only. Maybe keeping a narrow scope is not a bad thing for the library.

Anyway, thank you for your questions!

**Comment by asvetlov** [comment]
Please correct me if I'm wrong.
aiologic benchmark uses gevent/evenlet in 'patched' mode.
Thus, is measures not asyncio/threaded queue but asyncio/greenlet. It makes a huge difference; threaded and greenlet execution models are not interchangeable.

**Comment by asvetlov** [comment]
Thanks, your measures are very interesting.
Did you dig deeper? Have you ideas what are the main slowdown sources?

**Comment by asvetlov** [comment]
First, please let me describe the status quo.
`janus` is an open source project managed by volunteers.
The library was developed mostly by me in 2015. It belongs to aio-libs organization which is managed by volunteers also.
I paused my contribution to OSS for about last two years by private reasons. Think of it as a bus factor; that's life. 
Other aio-libs developers kept many projects (aiohttp, yarl, name it) running. I very appreciate their support.
`janus` don't attract many attention by its nature. 
Moreover, the latest published version was not broken. Github CI needed some love, that's true. Answering users questions is really great and important, don't get me wrong. But we have what we have. 
New contributors are welcome, sure!

Now I've found a time to return back. I have no guarantee to support it forever but I have an intention to do again more or less well. Everyone should decide want one use the library or not.

**Comment by asvetlov** [comment]
Regarding `janus` design. The api is established about 10 years ago. Change existing behavior breaks backward compatibility, we cannot accept it.

If you want to make a pull request with some improvements -- you are welcome!
But please be careful. 
In asyncio we spent many days trying to make queue and locks bug-free. Everything worked well in "normal" situation but tasks cancellation produced very non-obvious cases sometimes. 
For example, see https://github.com/python/cpython/commit/c47dacb69054 and https://github.com/python/cpython/commit/6b53d5fe04ea
From my experience, Mutex+Condition based implementation is slower but easier and safer by definition.

**Comment by asvetlov** [comment]
If you are asking for a link --yes, sure.

**Comment by asvetlov** [comment]
Great! Is there any chance to publish the test suite along with the source code?
