### ISSUE TITLE
Please upload version 0.3.1 to pypi

### ISSUE THREAD

**Issue by vlanse** [aio-libs/janus#76]
Need a version which includes 9b19e55e0f7c72b8e780c461e806392e68ff666d to be publicly available

**Comment by vlanse** [comment]
@jettify can you please help with this?

**Comment by asvetlov** [comment]
Let's mark it 1.0 -- the library is pretty stable

**Comment by jettify** [comment]
Before release we need to address https://github.com/aio-libs/janus/issues/2 I think, should be few lines change

**Comment by asvetlov** [comment]
Agree.
@jettify can you take a look?
I'm overwhelmed with Python 3.7 feature freeze

**Comment by jettify** [comment]
I will do release tonight or tomorrow

**Comment by jettify** [comment]
@vlanse new version deployed on PyPI https://pypi.python.org/pypi/janus/0.3.1

**Comment by jettify** [comment]
@asvetlov I decided to release 0.3.1 in order not to block anyone, as for 1.0.0 we can release it once #2 addressed. Fix is simple but I have not clue how to construct test case for that, may need your input there.

**Comment by asvetlov** [comment]
Ok
